# Generated by Django 5.2 on 2025-05-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_Passeios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=100)),
                ('localPartida', models.CharField(max_length=100)),
                ('horarioPartida', models.CharField(max_length=5)),
                ('grupoWhats', models.CharField(max_length=100)),
            ],
        ),
    ]
