# Generated by Django 5.2 on 2025-05-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_passeios',
            name='DataPasseio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
