# Generated by Django 5.2 on 2025-06-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0002_cad_passeios_datapasseio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_passeios',
            name='DataPasseio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
